export type BriefLabelKey = 'ask' | 'current' | 'warnings' | 'intel' | 'actions' | 'sources' | 'updated' | 'disaster' | 'offline' | 'official' | 'interp' | 'noWarn' | 'happening' | 'means';
type Dict = Record<BriefLabelKey, string>;
const en: Dict = { ask: 'Ask about weather, warnings or climate...', current: 'CURRENT SITUATION', warnings: 'ACTIVE WARNINGS', intel: 'WEATHER INTELLIGENCE', actions: 'WHAT SHOULD I DO?', sources: 'DATA SOURCES', updated: 'UPDATED', disaster: 'DISASTER MODE', offline: 'OFFLINE', official: 'OFFICIAL IMD WARNING', interp: 'WEATHERGPT INTERPRETATION', noWarn: 'No official warning reported', happening: 'WHAT IS HAPPENING?', means: 'WHAT DOES IT MEAN?' };
const L: Record<string, Dict> = {
  en,
  hi: { ask: 'मौसम, चेतावनी या जलवायु के बारे में पूछें...', current: 'वर्तमान स्थिति', warnings: 'सक्रिय चेतावनियाँ', intel: 'मौसम की जानकारी', actions: 'मुझे क्या करना चाहिए?', sources: 'डेटा स्रोत', updated: 'अपडेट', disaster: 'आपदा मोड', offline: 'ऑफ़लाइन', official: 'आधिकारिक IMD चेतावनी', interp: 'WEATHERGPT व्याख्या', noWarn: 'कोई आधिकारिक चेतावनी नहीं', happening: 'क्या हो रहा है?', means: 'इसका क्या मतलब है?' },
  ta: { ask: 'வானிலை, எச்சரிக்கை அல்லது காலநிலை பற்றி கேளுங்கள்...', current: 'தற்போதைய நிலை', warnings: 'செயலில் உள்ள எச்சரிக்கைகள்', intel: 'வானிலை நுண்ணறிவு', actions: 'நான் என்ன செய்ய வேண்டும்?', sources: 'தரவு மூலங்கள்', updated: 'புதுப்பிப்பு', disaster: 'பேரிடர் பயன்முறை', offline: 'ஆஃப்லைன்', official: 'அதிகாரப்பூர்வ IMD எச்சரிக்கை', interp: 'WEATHERGPT விளக்கம்', noWarn: 'அதிகாரப்பூர்வ எச்சரிக்கை இல்லை', happening: 'என்ன நடக்கிறது?', means: 'இதன் பொருள் என்ன?' },
  te: { ask: 'వాతావరణం, హెచ్చరికలు లేదా వాతావరణ మార్పుల గురించి అడగండి...', current: 'ప్రస్తుత పరిస్థితి', warnings: 'క్రియాశీల హెచ్చరికలు', intel: 'వాతావరణ సమాచారం', actions: 'నేను ఏమి చేయాలి?', sources: 'డేటా మూలాలు', updated: 'నవీకరణ', disaster: 'విపత్తు మోడ్', offline: 'ఆఫ్‌లైన్', official: 'అధికారిక IMD హెచ్చరిక', interp: 'WEATHERGPT వివరణ', noWarn: 'అధికారిక హెచ్చరిక లేదు', happening: 'ఏమి జరుగుతోంది?', means: 'దీని అర్థం ఏమిటి?' },
  ml: { ask: 'കാലാവസ്ഥ, മുന്നറിയിപ്പ് അല്ലെങ്കിൽ climate പറ്റി ചോദിക്കൂ...', current: 'നിലവിലെ സ്ഥിതി', warnings: 'സജീവ മുന്നറിയിപ്പുകൾ', intel: 'കാലാവസ്ഥ വിവരങ്ങൾ', actions: 'ഞാൻ എന്ത് ചെയ്യണം?', sources: 'ഡാറ്റ ഉറവിടങ്ങൾ', updated: 'അപ്ഡേറ്റ്', disaster: 'ദുരന്ത മോഡ്', offline: 'ഓഫ്‌ലൈൻ', official: 'ഔദ്യോഗിക IMD മുന്നറിയിപ്പ്', interp: 'WEATHERGPT വ്യാഖ്യാനം', noWarn: 'ഔദ്യോഗിക മുന്നറിയിപ്പില്ല', happening: 'എന്താണ് സംഭവിക്കുന്നത്?', means: 'ഇതിന്റെ അർത്ഥം?' },
  kn: { ask: 'ಹವಾಮಾನ, ಎಚ್ಚರಿಕೆ ಅಥವಾ ಹವಾಮಾನ ಬದಲಾವಣೆ ಬಗ್ಗೆ ಕೇಳಿ...', current: 'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ', warnings: 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು', intel: 'ಹವಾಮಾನ ಮಾಹಿತಿ', actions: 'ನಾನು ಏನು ಮಾಡಬೇಕು?', sources: 'ಡೇಟಾ ಮೂಲಗಳು', updated: 'ನವೀಕರಣ', disaster: 'ವಿಪತ್ತು ಮೋಡ್', offline: 'ಆಫ್‌ಲೈನ್', official: 'ಅಧಿಕೃತ IMD ಎಚ್ಚರಿಕೆ', interp: 'WEATHERGPT ವಿವರಣೆ', noWarn: 'ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆ ಇಲ್ಲ', happening: 'ಏನು ನಡೆಯುತ್ತಿದೆ?', means: 'ಇದರ ಅರ್ಥವೇನು?' },
  mr: { ask: 'हवामान, इशारे किंवा हवामान बदलाबद्दल विचारा...', current: 'सध्याची स्थिती', warnings: 'सक्रिय इशारे', intel: 'हवामान माहिती', actions: 'मी काय करावे?', sources: 'डेटा स्रोत', updated: 'अद्यतनित', disaster: 'आपत्ती मोड', offline: 'ऑफलाइन', official: 'अधिकृत IMD इशारा', interp: 'WEATHERGPT स्पष्टीकरण', noWarn: 'अधिकृत इशारा नाही', happening: 'काय घडत आहे?', means: 'याचा अर्थ काय?' },
};
export const briefLabels = (lang: string): Dict => L[lang] || en;
export const SPEECH_LANG: Record<string, string> = { en: 'en-IN', hi: 'hi-IN', ta: 'ta-IN', te: 'te-IN', ml: 'ml-IN', kn: 'kn-IN', mr: 'mr-IN' };
